In [131]:
#dependencies (matrix math) 
import numpy as np

In [132]:
#input data
input_data = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
output_labels = np.array([[0],
            [1],
            [1],
            [0]])

print(input_data)
print(output_labels)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
[[0]
 [1]
 [1]
 [0]]


In [ ]:
# sigmoid function
def activate(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [142]:
# 2 weight values
synaptic_weight_0 = 2*np.random.random((3,4)) - 1
synaptic_weight_1 = 2*np.random.random((4,1)) - 1

print(synaptic_weight_0)
print(synaptic_weight_1)

[[ 0.04934062  0.84961594 -0.47340646 -0.86807782]
 [ 0.47013193  0.54435606  0.81563171  0.86394414]
 [-0.97209685 -0.53127583  0.23355671  0.89803264]]
[[ 0.90035224]
 [ 0.11330638]
 [ 0.8312127 ]
 [ 0.28313242]]


In [141]:
for j in xrange(60000):

	# Forward propagate through layers 0, 1, and 2
    layer0 = input_data
    layer1 = activate(np.dot(layer0,synaptic_weight_0))
    layer2 = activate(np.dot(layer1,synaptic_weight_1))

    #calculate error for layer 2
    layer2_error = output_labels - layer2
    
    if (j% 10000) == 0:
        print "Error:" + str(np.mean(np.abs(layer2_error)))
        
    #Use it to compute the gradient
    layer2_gradient = l2_error*activate(layer2,deriv=True)

    #calculate error for layer 1
    layer1_error = layer2_gradient.dot(synaptic_weight_1.T)
    
    #Use it to compute its gradient
    layer1_gradient = layer1_error * activate(layer1,deriv=True)
    
    #update the weights using the gradients
    synaptic_weight_1 += layer1.T.dot(layer2_gradient)
    synaptic_weight_0 += layer0.T.dot(layer1_gradient)


Error:3.17606213494e-05
Error:2.93162545087e-05
Error:2.72212348725e-05
Error:2.5405665823e-05
Error:2.38171310776e-05
Error:2.24155517423e-05


In [139]:
#testing
print(activate(np.dot(array([0, 1, 1]), syn0)))

[ 0.99973427  0.98488354  0.01181281  0.96003643]
